### ISSUE TITLE
Verify the uniqueness of error number

### ISSUE THREAD

**Issue by lolski** [graknlabs/common#62]
Currently, there is no way for us to enforce the uniqueness of error numbers in the `ErrorMessage` class. Given that error numbers are inputted manually by the developer, it is easy to accidentally introduce duplication by mistake.

Error numbers must always be unique and we must find a better way to guarantee it. One proposal by Haikal is to add a test which uses reflection and check for the uniqueness across error objects that are declared.

**Comment by haikalpribadi** [comment]
This is solved by https://github.com/graknlabs/grakn/pull/5951 - we can enforce the same strategy on other systems, e.g. client-java
